# Generated by Django 2.1.2 on 2018-12-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnd_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_classic',
        ),
    ]
