# Generated by Django 2.1.2 on 2018-12-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnd_api', '0002_remove_rating_is_classic'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_classic',
            field=models.BooleanField(default=False),
        ),
    ]
