# Generated by Django 2.1.2 on 2018-12-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnd_api', '0004_auto_20181216_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fav_tracks',
            field=models.TextField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='album',
            name='least_fav_track',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
